layout_spectrum: 0.4526944
color:
  saturation: 0.09318996
  brandStrength: 0.9186779
  lightness: 0.1164875
  rhythmicContrast: 0.6290323
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.8768773
name: Jeremiah Sahabu Photography
